# Writes FIRMWARE_VERSION_STRING into OUT from `git describe` against the
# release tags: "Bandolibre v1.2-alpha" on a tagged commit,
# "Bandolibre v1.2-alpha-3-g9f91cb8-dirty" for a build past it or with local
# changes. Run as `cmake -DOUT=<header> -DSRC=<dir> -P version.cmake` on every
# build (see CMakeLists.txt); OUT is only rewritten when the text changes, so
# an unchanged version recompiles nothing.

execute_process(
    COMMAND git describe --tags --match "bandolibre-v*" --dirty
    WORKING_DIRECTORY "${SRC}"
    OUTPUT_VARIABLE describe
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE result
)
if(NOT result EQUAL 0 OR describe STREQUAL "")
    # Not a git checkout (e.g. a source archive), or no release tag reachable.
    set(describe "bandolibre-unknown")
endif()
string(REGEX REPLACE "^bandolibre-" "Bandolibre " version "${describe}")

set(content "/* Generated by cmake/version.cmake - do not edit. */\n#define FIRMWARE_VERSION_STRING \"${version}\"\n")
if(EXISTS "${OUT}")
    file(READ "${OUT}" previous)
else()
    set(previous "")
endif()
if(NOT previous STREQUAL content)
    file(WRITE "${OUT}" "${content}")
endif()
